apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gxud
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gxud
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gxud
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gxud
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gxud
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lcem-tenant/rhtap-demo-app/hacbs-test-project-gxud@sha256:1a63016e35c243b32945c8533cee60a791781f5a9baa53512a6745c10e4364e2
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
